### ISSUE TITLE
session commit silently does nothing

### ISSUE THREAD

**Issue by philmain28** [renalreg/ukrdc-cupid#25]
https://github.com/renalreg/ukrdc-cupid/blob/e1861ef4165ff759616fdc0d1daeb49e9220ac03/src/ukrdc_cupid/core/store/models/structure.py#L331

This is the cupid model for keeping the lookup tables in sync with the ukrr it works as intended to this point but for some reason the add +commit doesn't seem to actually do anything. Complicating matters I have updated to sqla 2 which I think may have contributed in some sort of way. 

@George-D-S @andyatterton any ideas?

**Comment by George-D-S** [comment]
Not sure, though a general comment would be that I don't think this should be part of the CUPID repo but rather a specific process which syncs the tables from renalreg to UKRDC.

I also think the models should in another repo entirely (though possibly one of the existing ones) as there will be occasions where we want to use them without needing the entire CUPID repo.

**Comment by philmain28** [comment]
Okay my logic was that because it is loading data into the ukrdc that makes it a cupid thing. Also I thought it could eventually have and api route and be scheduled via mirth. I can see your point on the models me a Joel had very long debates on the topic of is cupid a library or a service. Given a big chunk of the code is the xml to orm translation my opinion is that to do that would be more or less equivalent to seperating out the api.
