### ISSUE TITLE
Ability to test RDA Converter instance

### ISSUE THREAD

**Issue by George-D-S** [renalreg/ukrdc-cupid#28]
I'd like the ability to do a basic check of whether a deployed instance of RDA Converter is working. This is as a pre-check before we process files for a site.

Two possible ideas.

1) The ability to disable the "store" functionality via a URL parameter. A valid XML file could then be submitted then the response compared with a known converted XML document.

2) An additional URL which just returns the current version etc.

**Comment by philmain28** [comment]
@George-D-S  did you mean this to be an issue on this repo?

**Comment by George-D-S** [comment]
Oops, moved to the correct repo.
